{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    # Map AWS Secrets Manager keys to Kubernetes secret keys
  - secretKey: DB_HOST
    remoteRef:
      key: glodios/postgresdb 
      property: DB_HOST

  - secretKey: DB_PORT
    remoteRef:
      key: glodios/postgresdb
      property: DB_PORT

  - secretKey: DB_USER
    remoteRef:
      key: glodios/postgresdb
      property: DB_USER

  - secretKey: DB_PASSWORD
    remoteRef:
      key: glodios/postgresdb
      property: DB_PASSWORD
      
  - secretKey: DB_NAME
    remoteRef:
      key: glodios/postgresdb
      property: DB_NAME
  
  # - secretKey: REDIS_URL
  #   remoteRef:
  #     key: glodios/redis  # YOUR SECRET NAME IN AWS
  #     property: REDIS_URL

    # Add more as needed...
{{- end }}
