apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::887709589787:role/glodios-node20260501072002862900000001
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    # User 1 - Full admin
    - userarn: arn:aws:iam::887709589787:user/neeraj-joon
      username: k8s-admin
      groups:
        - system:masters

    # User 2 - Monitoring read-only
    - userarn: arn:aws:iam::887709589787:user/k8s-monitoring
      username: k8s-monitoring
      groups:
        - monitoring-read-only

    # User 3 - Backend dev
    - userarn: arn:aws:iam::887709589787:user/k8s-backend-dev
      username: k8s-backend-dev
      groups:
        - backend-admins

kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-01T07:44:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "979"
  uid: 592b0dbd-6f22-4689-8448-da7ee66595a1
