apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  
  source:
    repoURL: https://github.com/Neerajj00n/PG-EKS-Gitops.git # ← CHANGE THIS
    targetRevision: main
    path: /EKS/gitops/infra/  # All infra manifests here
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
