# ============================================================
# Prometheus
# ============================================================
prometheus:
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
   # serviceMonitorSelectorNilUsesHelmValues: false

    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "observability"
        effect: "NoSchedule"

    nodeSelector:
      role: observability

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

# ============================================================
# Grafana
# ============================================================
grafana:
  # deploymentStrategy:
  #   type: Recreate
  enabled: true
  replicas: 1
  adminPassword: admin

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

  nodeSelector:
     role: observability

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp3

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
          isDefault: true
          jsonData:
            timeInterval: 30s

        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: false

          
  ingress:
    name: grafana-ingress
    enabled: true
    ingressClassName: alb
    namespace: monitoring
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:887709589787:certificate/66b19ef6-f639-484c-8f97-571df7bb0dd1"
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: "glodios-alb-group"

    hosts:
      - grafana.glodios.com
    path: /
    pathType: Prefix

# ============================================================
# Alertmanager
# ============================================================
alertmanager:
  enabled: true
  alertmanagerSpec:
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "observability"
        effect: "NoSchedule"

    nodeSelector:
      role: observability

    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# ============================================================
# Prometheus Operator
# ============================================================
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

  nodeSelector:
    role: observability

# ============================================================
# Node Exporter — DaemonSet, runs on ALL nodes
# ============================================================
nodeExporter:
  enabled: true
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

# ============================================================
# kube-state-metrics
# ============================================================
kubeStateMetrics:
  enabled: true

